/*
 * OpenTerps
 *
 * An Open API that contains information about terpenes, the effects, and the cannabis varieties that contain them.
 *
 * API version: 0.0.1
 * Contact: benjamminredden@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelApiResponse struct {
	Code int32 `json:"code,omitempty"`
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
}
